#makefile for kcdread
#very simple version for gcc


kcdread: sensecodes.cpp main.cpp direntry.cpp kmsi_direct.cpp virtualdevice.cpp
	g++ -D_GCC -o kcdread sensecodes.cpp main.cpp direntry.cpp kmsi_direct.cpp virtualdevice.cpp 
